### PR TITLE
Cherry pick PR 704 to domains+effects

### PR DESCRIPTION
**Pull request by bikallem**
Cherry pick PR #704 commits.

### CODE REVIEW

**Comment by ctk21** [comment]
I notice that we have taken the non-deprecating route for the `4.12+domains+effects` branch for these changes. 

The alternative option would be to deprecate the old functions and add `Domain.cpu_relax ()`.

Are we certain we want this more aggressive route?

**Comment by bikallem** [comment]
No opinion either way. I was mostly following the precedent set by earlier PR with regards to syncing features in 5.00 and 4.12.0+domains+... [PR 689](https://github.com/ocaml-multicore/ocaml-multicore/pull/689).

**Comment by bikallem** [comment]
Closing this PR and opening a new one to deprecate the removed and moved functions.

**Pull request closed without merging**
