### PR TITLE
Blocked signal infinite loop fix

### PR DESCRIPTION
**Pull request by sadiqj**
This is a fix for https://github.com/ocaml-multicore/ocaml-multicore/issues/703

The problem stems from https://github.com/ocaml-multicore/ocaml-multicore/blob/5.00/runtime/signals.c#L152 where we need to check whether a signal has been delivered that races our entry in to a blocking section. If we have a waiting signal blocked then this loop will continue forever (or until another thread processes that waiting signal).

To fix this we introduce a monotonic `recorded_signals_counter`. We can replace the earlier conditional with a check that the `recorded_signals_counter` has not increased since we entered the blocking section. This also has the upside that it's cheaper than checking each of the pending counts for each signal we do at the moment.

### CODE REVIEW

**Comment by kayceesrk** [comment]
Does this PR need a testcase?

**Comment by sadiqj** [comment]
> Does this PR need a testcase?

We're working on one. It's tricky to build something that's not brittle.

**Comment by sadiqj** [comment]
So there's now a test which hangs on 5.00 but will pass on this PR most of the time (thanks @Engil for some debugging help). The rest of the time it will segfault. We know what the cause of the segfault is, we'll create an issue for it.

**Comment by sadiqj** [comment]
While https://github.com/ocaml-multicore/ocaml-multicore/issues/734#issuecomment-962033324 is an issue I've disabled the included test in this PR.

**Comment by sadiqj** [comment]
I'm going to close this for now. The consensus at the working group was to move from counting signals to coalescing them, so this would probably need a rewrite regardless. The issue remains open.

**Pull request closed without merging**
