### PR TITLE
One more location to poll for interrupts without lock

### PR DESCRIPTION
**Pull request by kayceesrk**
Similar to #353.

### CODE REVIEW

**Comment by stedolan** [comment]
If we're optimising this, the `cpu_relax` should probably be in an else block, rather than unconditional. We don't want to `PAUSE` if there's an interrupt pending.

**Comment by kayceesrk** [comment]
Good point. I've moved `cpu_relax` to the else branch.

**Comment by ctk21** [comment]
The functionality looks correct to me. 

However I wonder if we take the opportunity to clean things up further, although the code looks different in `caml_ml_domain_cpu_relax` both are doing the same thing (at least conceptually). Might it be better to have a single function that does the fast-path check, locking and interrupt handling which is called from both (e.g. an inline function `domain_cpu_relax`)? Or use `caml_ml_domain_cpu_relax` from here?

**Comment by kayceesrk** [comment]
Good point. Let me cleanup the code.

**Comment by kayceesrk** [comment]
@ctk21 I've factored out common code.

**Comment by ctk21** [comment]
LGTM

**Pull request merged**
