### PR TITLE
Deprecate Sync and timer_ticks from Domain

### PR DESCRIPTION
**Pull request by bikallem**
Syncs 4.12.0+domains+effects with the mainline 5.00 branch, specifically the change from PR #704

### CODE REVIEW

**Comment by ctk21** [comment]
I think this works and should provide a route for people to have the same code run on the `5.00` branch alongside the `4.12` multicore branches.

**Review by Sudha247 — COMMENTED** [review]
Looks good! I think this sits well with both the old and new functions, too.

**Comment by bikallem** [comment]
> I think this works and should provide a route for people to have the same code run on the `5.00` branch alongside the `4.12` multicore branches.

/cc @ctk21 should I take this as an approval?

**Comment by ctk21** [comment]
LGTM, merging

**Comment by bikallem** [comment]
Thanks.

**Pull request merged**
