### PR TITLE
Refactor domain interrupts and synchronisation

### PR DESCRIPTION
**Pull request by stedolan**
Massive refactor of domain synchronisation logic.

The new features is that domain termination now works, and domains can yield without spinning.

At domain termination, the minor heap is emptied, and active shared heap pools are moved into a global list, so that some other domain will pick them up and start sweeping them.

Yielding uses the new primitives yield, interrupt and critical sections, and is implemented via condition variables rather than atomics and spinning (so that yielding does actually sleep).

### CODE REVIEW

**Comment by stedolan** [comment]
The only test failure is `Domain.join`, which is disabled in this code. (There's now enough support to implement `Domain.join` in OCaml, but I haven't done that yet)

**Comment by kayceesrk** [comment]
With this PR, as I undestand, these mechanisms can be implemented in OCaml rather than C: https://github.com/ocamllabs/ocaml-multicore/issues/100, https://github.com/ocamllabs/ocaml-multicore/issues/118, https://github.com/ocamllabs/ocaml-multicore/issues/117, https://github.com/ocamllabs/ocaml-multicore/issues/102, https://github.com/ocamllabs/ocaml-multicore/issues/73. These are unnecessary: https://github.com/ocamllabs/ocaml-multicore/issues/90. @stedolan, would be useful if you implement https://github.com/ocamllabs/ocaml-multicore/issues/100 as an example.

**Comment by stedolan** [comment]
> With this PR, as I undestand, these mechanisms can be implemented in OCaml rather than C: #100, #118, #117, #102, #73. These are unnecessary: #90. @stedolan, would be useful if you implement #100 as an example.

Yes to all except #73. We can't support preemption until it's possible to make a continuation in an arbitrary possibly-callback context, which requires doing #146 first.

**Comment by kayceesrk** [comment]
`parallel/join` test fails. But merging now as we will reimplement join in OCaml.

**Pull request merged**
