### PR TITLE
Promote to 4.04.2

### PR DESCRIPTION
**Pull request by kayceesrk**
This PR brings multicore up to 4.04.2. The diff is too large to be useful. The gist is that all of the tests, which have not been disabled due to missing features, pass on x86_64 Linux [0]. 

Along with a list of runtime system things that were already broken or not implemented in 4.02.2 (weak refs, finalisers, ocamldebug, marshalling of closures), the following newer features are not implemented/broken: ephemerons, GC latency improvements, instrumented runtime, spacetime profiler. These need to be fixed in due course.

In the meantime, I propose to merge this PR and keep hacking. I've created a tag for 4.02.2+multicore [1]. 

----

[0] https://travis-ci.org/ocamllabs/ocaml-multicore/builds/355147011?utm_source=github_status&utm_medium=notification
[1] https://github.com/ocamllabs/ocaml-multicore/tags

### CODE REVIEW

**Comment by kayceesrk** [comment]
The only test that fails now is `parallel/timing.ml`. This is a known issue #164.

**Comment by jordwalke** [comment]
It's great to see this happening!

**Comment by kayceesrk** [comment]
Promoting to 4.06.0 next. Going forward, the plan is to have the multicore branch track OCaml releases.

**Comment by yallop** [comment]
This will be very useful!

Could you please leave a 4.04.* branch (and perhaps a tag) around when promoting to 4.06.*?

**Comment by kayceesrk** [comment]
@yallop Good idea. I'll create a tag for 4.04.2 before merging 4.06.0.

**Pull request merged**
