### PR TITLE
remove dead code and clear up comments in the minor gc

### PR DESCRIPTION
**Pull request by sadiqj**
This should be a non-functional change. @ctk21 and I are clearing up and commenting the minor and major gc files.

### CODE REVIEW

**Comment by kayceesrk** [comment]
Looks like there is an interesting failure: https://github.com/ocaml-multicore/ocaml-multicore/pull/697/checks?check_run_id=3937920491#step:4:2578. Paging @Engil.

**Comment by kayceesrk** [comment]
The changes look good to me.

**Comment by abbysmal** [comment]
@kayceesrk the `multicore_systhreads` is a thing I'm investigating at the moment.
I do not think it is related to this branch. (I've seen it somewhere else but failed to reproduce it so far.)

**Comment by ctk21** [comment]
Regarding the `parallel/multicore_systhreads.ml` CI failure. We have merged #695 which includes potential fixes from trunk alignment. 

I've rebased this PR with #695 merged.

**Comment by kayceesrk** [comment]
LGTM

**Pull request merged**
