### PR TITLE
Promote to 4.02.2

### PR DESCRIPTION
**Pull request by kayceesrk**

### CODE REVIEW

**Comment by kayceesrk** [comment]
@stedolan Merged latest master to this PR.

**Comment by kayceesrk** [comment]
@stedolan @lpw25 Any comments on this PR?

**Comment by lpw25** [comment]
It's pretty impossible to review it, but I think you should just go ahead and merge.

**Comment by kayceesrk** [comment]
Sorry about the massive PR. It just brings in all of the file re org done in 4.02.2. There wasn't anything interesting wrt multicore.

**Pull request merged**
